[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "optimisation-tools"
version = "2025.12.22"
requires-python = ">= 3.8"
authors = [
    {name = "Chris Rogers"}
]
license = "GPL-3.0-or-later"
